In [1]:
import pandas as pd
import math
import matplotlib as mpl
import matplotlib.pyplot as plt

In [2]:
music_pd=pd.read_csv('full_music_data.csv')
music_pd=music_pd.drop(['artist_names','mode','key','explicit','popularity','year','release_date','song_title (censored)'],axis=1)
artist_pd=pd.read_csv('data_by_artist.csv')
artist_pd=artist_pd.drop(['mode','key','duration_ms','popularity','count'],axis=1)

,artist_name,artist_id,danceability,energy,valence,tempo,loudness,acousticness,instrumentalness,liveness,speechiness
0,Frank Sinatra,792507,0.384478,0.238017,0.364288,110.181698,-14.271141,0.735648,0.020855,0.232106,0.049614
1,Vladimir Horowitz,119107,0.343210,0.118844,0.225951,94.900679,-23.193418,0.990070,0.879508,0.183812,0.043360
2,Johnny Cash,816890,0.619803,0.449381,0.680662,115.037747,-11.593104,0.685637,0.022647,0.242243,0.098216
3,Billie Holiday,79016,0.572637,0.201368,0.498934,109.912172,-13.225966,0.908499,0.013064,0.217727,0.062432
4,Bob Dylan,66915,0.512598,0.477932,0.551934,126.160149,-11.184330,0.562567,0.034211,0.308978,0.064535
...,...,...,...,...,...,...,...,...,...,...,...
5849,Natalie La Rose,3359519,0.830000,0.520000,0.735000,104.990000,-8.714000,0.000792,0.000013,0.065600,0.037600
5850,Sarah Ross,3381566,0.721000,0.944000,0.626000,85.002000,-5.982000,0.013000,0.000000,0.320000,0.159000
5851,Rotimi,3410250,0.637000,0.501000,0.431000,103.993000,-6.148000,0.229000,0.000059,0.099000,0.187000
5852,Jillian Jacqueline,3455945,0.547000,0.672000,0.283000,155.791000,-5.023000,0.304000,0.000000,0.099600,0.049600
5853,Jaira Burns,3639618,0.566000,0.769000,0.385000,170.036000,-4.342000,0.018300,0.000000,0.108000,0.087200

In [23]:
artist_attr={}
for i in range(artist_pd.shape[0]):
    artist_attr[artist_pd.loc[i]['artist_id']]=artist_pd.loc[i]['artist_name']

In [4]:
for col in music_pd.columns:
    if(col=='artist_names' or col=='artists_id'): continue
    music_pd[col]=(music_pd[col]-music_pd[col].mean())/(music_pd[col].std())

In [12]:
music_pd

,artists_id,danceability,energy,valence,tempo,loudness,acousticness,instrumentalness,liveness,speechiness,duration_ms
0,[178301],0.449176,-0.639930,-1.555980,0.370169,-0.459199,-0.994756,1.686007,-0.617400,-0.184035,1.825053
1,[178301],2.119573,-0.787390,-1.370321,0.021770,-0.502415,-1.146292,0.082297,-0.578712,0.882922,3.146530
2,[178301],0.875920,-0.012280,-0.763062,0.682245,0.491145,-1.140637,0.805251,0.531955,-0.343027,1.770773
3,[625201],1.430686,0.634275,1.225033,-0.474364,0.440628,-0.879408,-0.460721,-0.609878,-0.327259,0.604979
4,[625201],0.821053,1.110684,1.426163,-0.130008,-0.378294,-0.404445,-0.460830,0.429862,-0.325945,0.242062
...,...,...,...,...,...,...,...,...,...,...,...
98335,[690254],-1.526038,1.352670,0.702868,-1.286316,0.734256,-0.028432,-0.460835,2.724274,0.334990,-1.126757
98336,[690254],1.058810,0.218362,1.441635,-0.304809,0.063529,-0.879408,-0.393311,-0.478231,0.056425,0.230061
98337,[690254],1.113677,0.660742,1.275316,-0.248101,-0.250029,-0.851136,-0.460795,-0.440618,-0.352225,-0.736888
98338,[690254],0.156552,0.441443,-0.001088,1.422853,0.026037,-1.170775,-0.332759,-0.403004,2.170629,-0.055667
98339,[690254],0.119974,1.246801,1.275316,0.891666,0.616450,-0.928035,-0.430963,0.376128,-0.322004,-0.931331

In [16]:
artist_music_attr={}
for i in range(music_pd.shape[0]):
    ids=music_pd.loc[i]['artists_id']
    ids=ids.lstrip('[').rstrip(']').split(",")
#     print(ids,len(ids),ids[0])
#     input()
    for artist_id in ids:
        artist_id=int(artist_id)
        if(artist_music_attr.setdefault(artist_id)==None):
            artist_music_attr[artist_id]={}
            for key,val in music_pd.loc[i].drop('artists_id').to_dict().items():
                artist_music_attr[artist_id][key]=val
            artist_music_attr[artist_id]['cnt']=1
        else:
            for key,val in music_pd.loc[i].drop('artists_id').to_dict().items():
                artist_music_attr[artist_id][key]+=val
            artist_music_attr[artist_id]['cnt']+=1

In [36]:
# print(artist_music_attr)
with open('q2.txt','w+',encoding='utf-8') as f2:
    for key,val in artist_music_attr.items():
#         print(key,artist_attr[key])
        f2.write(artist_attr[key]+","+str(key))
        for k,v in val.items():
            if(k=="cnt"): continue
            f2.write(","+str(v/artist_music_attr[key]['cnt']))
        f2.write("\n")

In [32]:
for key,val in artist_music_attr.items():
    ans=""
    for k in val.keys():
        ans+=k+"_mean,"
    break
print(ans)

danceability_mean,energy_mean,valence_mean,tempo_mean,loudness_mean,acousticness_mean,instrumentalness_mean,liveness_mean,speechiness_mean,duration_ms_mean,cnt_mean,